### ISSUE TITLE
`impl From<[(K, V); N]>` for collections

### ISSUE THREAD

**Issue by allan2** [rust-lang/rustc-hash#21]
It would be nice to be able to use the nifty hash map construction that was added to `std::collections::HashMap` in 1.56.0.

Currently supported:
```rust
use rustc_hash::FxHashMap;
use std::collections::HashMap;

let std_map = HashMap::<u32, u32>::from([(22, 44)]);  // awesome!
let fx_map = Vec::from([(22, 44)]).into_iter().collect::<FxHashMap<u32, u32>>();  // meh

```

Nice-to-have goal:
```rust
let fx_map = FxHashMap::<u32, u32>::from([(22, 44)]);   // too bad, won't work today
```

The description above `impl<K, V; N>` in [`collections/hash/map.rs`](https://github.com/rust-lang/rust/blob/master/library/std/src/collections/hash/map.rs) helps to explain why this is:
>To that end, this impl is defined using RandomState as the concrete
>type of S, rather than being generic over `S: BuildHasher + Default`.
>It is expected that users who want to specify a hasher will manually use
>`with_capacity_and_hasher`.
>**If type parameter defaults worked on impls, and if type parameter
>defaults could be mixed with const generics, then perhaps
>this could be generalized.**

I'm thinking there are two options to get this working:
1. wait for things to be added to the Rust language, after which `HashMap` will implement it  <-- *when will this happen*
2. use a struct for `FxHashMap` instead of a type alias  <-- *more work*

What do the maintainers and everyone else think?

**Comment by bluss** [comment]
What about `FxHashMap::<u32, u32>::from_iter([(22, 44)]);`?  Should be fine in 2021 edition

**Comment by allan2** [comment]
I didn't know you could do that! It's nicer for sure. I would still like to see `from([(22, 44)])` supported.

**Comment by utkarshgupta137** [comment]
+1

**Comment by Nilstrieb** [comment]
This would be useful, but there's nothing we can do here, so I'm closing this.
https://doc.rust-lang.org/1.75.0/std/collections/hash_map/struct.HashMap.html#impl-From%3C%5B(K,+V);+N%5D%3E-for-HashMap%3CK,+V%3E
The impl hardcodes `RandomState`, we cannot change that in this repository. Use `from_iter` as suggested by bluss.
We will not create a custom struct, that would be a huge maintenance burden and make for a worse experience overall.
