### ISSUE TITLE
Collision between integer as string hashes

### ISSUE THREAD

**Issue by zazabe** [rust-lang/rustc-hash#26]
I wonder if these 2 strings should result in the same hash?

```rust
#[test]
fn collisions() {
    // fails, both hashes are equal!
    assert_ne!(rustc_hash_fx_one("100000019"), rustc_hash_fx_one("100000094"));
}

pub fn rustc_hash_fx_one<H: Hash>(hashable: H) -> u64 {
    let mut hasher = rustc_hash::FxHasher::default();
    hashable.hash(&mut hasher);
    hasher.finish()
}
```
In another test, I saw that there were 2508 collisions between 100000000 and 100100000, when hashed as a string...

**Comment by Nilstrieb** [comment]
fxhash has many collisions, that's inevitable with such a simple hash. I wouldn't recommend using it for longer string keys, it's mostly optimized for integer keys.

**Comment by Nilstrieb** [comment]
Closing this, as we don't care about collisions, we only care about rustc being fast.
