### ISSUE TITLE
short hashing macro?

### ISSUE THREAD

**Issue by chris-ha458** [rust-lang/rustc-hash#27]
I often find myself using short hashes.

```
use std::collections::hash_map::DefaultHasher;
let data:Vec<u8> = vec![1, 2, 3, 4];
let mut hasher = DefaultHasher::new();
hasher.write(&$data);
hasher.finish()
```

I think there are many use cases where we hash a single sequence of data.

I encapsulated the above idea into a macro
```
macro_rules! default_hash {
    ($data:expr) => {{
        use std::collections::hash_map::DefaultHasher;
        let mut hasher = DefaultHasher::new();
        hasher.write(&$data);
        hasher.finish()
    }};
}
```
that can be used as such
`let hash2 = default_hash!(data);`
I then extended this idea further

```
macro_rules! generic_hash {
    ($hasher_type:ty, $data:expr) => {{
        use std::hash::Hasher;
        let mut hasher: $hasher_type = Default::default();
        hasher.write(&$data);
        hasher.finish()
    }};
}
```
which can be used as such
```
let highway = generic_hash!(HighwayHasher, data);
let xxh = generic_hash!(Xxh3, data);
```

I hope to benefit others that have to deal with these kind of boilerplate.
Which would be the best way?

1. Find a way for it to be included here. In the rust standard library code dealing with hashes
2. A separate crate that includes the above, and possibly more (hash with a seed/secret)
3. It is not idiomatic to share code with this kind of function and scope (or this macro itself is not idiomatic, performant or safe) and it should only live in my own individual code.

I guess 2. can also be a path towards 1.
I do not have a lot of experience contributing to core rust so if there are other resources I should consult before discussing here, feel free to let me know

**Comment by Nilstrieb** [comment]
1.71 added https://doc.rust-lang.org/1.75.0/std/hash/trait.BuildHasher.html#method.hash_one which simplifies this

**Comment by Nilstrieb** [comment]
Closing because the standard library method already does this.
