### ISSUE TITLE
New version on crates.io

### ISSUE THREAD

**Issue by ZhaoXiangXML** [rust-lang/rustc-hash#36]
According to https://crates.io/crates/rustc-hash, it was last update about 4 years ago on Feb. 8th, 2020. It appears there has been some new commits on GitHub, is there by any chance this crate is going to be updated on crates.io?

Another problem is there's no tag of release for the last version, or any version.

I'm wondering if we can use the most recent version of rustc-hash from crates.io.

Thank you

**Comment by WaffleLapkin** [comment]
We planned to release a new version, but looks like this died out because we couldn't find a person with the permissions to publish new versions... I'll try to look what can be done with this.

**Comment by WaffleLapkin** [comment]
I started a thread on zulip: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/rustc-hash/near/431004426

**Comment by ZhaoXiangXML** [comment]
Any news?

**Comment by WaffleLapkin** [comment]
No one from the compiler team has stepped up to publish a new version.

**Comment by ZhaoXiangXML** [comment]
Well guess we won't be able to use the new version any time soon. Thank you for your time.

**Comment by WaffleLapkin** [comment]
you can always add it as a git dependency with rev=...

**Comment by riking** [comment]
Release has been published.

**Comment by nnethercote** [comment]
1.2.0 was published but then yanked due to some problems that are still being worked through, including #43. Hopefully a fixed version will be published soon.

**Comment by Havunen** [comment]
2.0.0 seems to be available, I guess this issue can be closed?

**Comment by ZhaoXiangXML** [comment]
Would you please create a GitHub tag for the new version? Thanks.

**Comment by Nilstrieb** [comment]
:+1: done
