### ISSUE TITLE
v1.2.0 seems to break without `std`

### ISSUE THREAD

**Issue by vados-cosmonic** [rust-lang/rustc-hash#42]
It seems that the latest version of `rustc-hash` has a a small bug -- it attempts to use `std` without first checking for the feature flag:

```
   Compiling rustc-hash v1.2.0
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-hash-1.2.0/src/seeded_state.rs:1:5
  |
1 | use std::collections::{HashMap, HashSet};
  |     ^^^ use of undeclared crate or module `std`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `rustc-hash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

The bug seems to be [in `seeded_state.rs`](https://github.com/rust-lang/rustc-hash/blob/master/src/seeded_state.rs#L1), as [the module is *not* guarded by the `std` feature](https://github.com/rust-lang/rustc-hash/blob/master/src/lib.rs#L28). 

For context, the dependency that I was actually trying to build that uses `rustc-hash` is [`wasmtime`](https://github.com/bytecodealliance/wasmtime).

**Comment by lqd** [comment]
IIUC this should be fixed by #41

**Comment by zimond** [comment]
@davidtwco please consider yank 1.2.0

**Comment by davidtwco** [comment]
I've yanked 1.2.0

**Comment by t3hmrman** [comment]
Appreciate it @davidtwco ! :bow: Confirming that builds are :green_circle: on my side.

**Comment by vados-cosmonic** [comment]
Appreciate it @davidtwco ! 🙇 Confirming that builds are 🟢 on my side, closing this!
